import "./globals.css";

import Provider from "@/context/AuthContext";
import SideNav from "@/components/sidenav/page";
import ThemeProviderMode from "./themeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ThemeProviderMode>
            <main className="flex flex-row">
              <SideNav />
              <div className="ml-[255px]">{children}</div>
            </main>
          </ThemeProviderMode>
        </Provider>
      </body>
    </html>
  );
}
