import "./globals.css";

import Provider from "@/context/AuthContext";
import ThemeProviderMode from "./themeProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ThemeProviderMode>{children}</ThemeProviderMode>
        </Provider>
      </body>
    </html>
  );
}
